Отчет по Теме #10 выполнил(а):
- Охлупин Константин Алексеевич
- ИВТ-21-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |


знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа 
### 1) Вам нужно написать программу, которая будет считать числа Фибоначчи для 100 и запустить ее без этого декоратора и с ним, посмотреть на разницу во времени решения поставленной задачи

```python
from functools import lru_cache

@lru_cache(None) 
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:

        return 1
    return fibonacci(n - 1) + fibonacci(n-2)

if __name__ == '__main__':
    print(fibonacci(100))

```
### Результат.
![ex1](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Lab/101.png)

## Выводы
fibonacci(n) - функция для вычисления числа Фибоначчи с использованием рекурсии. Декоратор @lru_cache(None) применен для кэширования результатов и повышения эффективности, чтобы избежать повторных вычислений.


### 2) Напишите декоратор для функции, который будет принимать все параметры вызываемой функции (имя, возраст) и проверять чтобы возраст был больше 0 и меньше 130.

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]
        
        if age < 0 or age > 130:
            age = 'Недопустимый возраст' 
            input_func(name, age)
    return output_func

@check
def personal_info(name, age):
    print (f"Name: {name} Age: {age}")

if __name__ == '__main__':
    personal_info('Владимир', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138, 15, 48, 2)
```

### Результат.
![ex2](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Lab/102.png)

## Выводы
check(input_func) - функция-декоратор, принимающая другую функцию input_func. Внутри себя определена функция output_func(*args), которая проверяет возраст (второй аргумент) на корректность (в пределах от 0 до 130). Если возраст некорректен, заменяет его на строку 'Недопустимый возраст' и вызывает исходную функцию input_func с именем и скорректированным возрастом.
personal_info(name, age) - функция, предоставляющая персональную информацию. Применена декорация @check, чтобы проверить корректность возраста перед выводом информации.

### 3) Воспользуйтесь исключениями, чтобы неподходящий тип данных не ломал ваш сайт. Также дополнительно можете обернуть весь код функции в try/except/finally для того, чтобы программа вас оповестила о том, что выявлена какая-то ошибка или программа успешно выполнена. 

```python
def data (*args): 
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print (ex)
    except Exception as ex:
        print (ex)
    finally:
        print('Вся информация обработана')

if __name__ == '__main__':
    data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```

### Результат.
![ex3](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Lab/103.png)

## Выводы
Если возникают исключения внутри цикла или при обращении к длине аргумента, они ловятся в соответствующих блоках except, и сообщения об ошибках выводятся.


### 4) Продолжая работу над сайтом, вы решили написать собственное исключение, которое будет вызываться в случае, если в функцию проверки имени при регистрации передана строка длиннее десяти символов, а если имя имеет допустимую длину, то в консоль выводиться “Успешная регистрация” Михаил А. Панов


```python
class NegativeValueException(Exception):
    pass

def check_name (name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '123456789'
    check_name (name)
```
### Результат.
![ex4](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Lab/104.png)

### Выводы
NegativeValueException - пользовательское исключение (наследник Exception), которое определено в классе.
check_name(name) - функция, принимающая аргумент name. Внутри функции проверяется длина имени. Если длина больше 10 символов, возбуждается исключение NegativeValueException с сообщением 'Длина более 10 символов'. В противном случае, выводится сообщение 'Успешная регистрация'.


### 5) После запуска сайта вы поняли, что вам необходимо добавить логгер, для отслеживания его работы. Готовыми вариантами вы не захотели пользоваться, и поэтому решили создать очень простую пародию. Для этого создали две функции: __init__() (вызывается при создании класса декоратора в программе) и __call__() (вызывается при вызове декоратора). Создайте необходимый вам декоратор. Выведите все логи в консоль.

```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод -_init успешный запуск') 
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__) 
        self.func()
        print('> Проверка безопасного выключения')
@SiteChecker
def site():
    print('Усердная работа сайта')
if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```

### Результат.
![ex5](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Lab/105.png)

### Выводы
SiteChecker - класс, который принимает функцию в конструкторе и хранит ее в атрибуте func. Реализует метод __call__, который вызывается при вызове объекта этого класса.
__init__(self, func) - конструктор класса, выводит сообщение о успешном запуске и сохраняет переданную функцию в атрибут func.
__call__(self) - метод, который выводит сообщение о проверке перед запуском, имя функции (метода) и вызывает саму функцию. Затем выводит сообщение о проверке безопасного выключения.
@SiteChecker - декоратор, примененный к функции site.
site() - функция, которая выводит сообщение о усердной работе сайта.
В блоке __main__ выводится сообщение о запуске сайта, вызывается функция site(), и выводится сообщение о выключении сайта.


## Самостоятельная работа 
### 1)  Помогите Вовочке в его начинаниях и напишите такой декоратор. Подсказка: необходимо использовать модуль time Декоратор необходимо использовать для этой функции:

```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Функция {func.__name__} выполнилась за {execution_time:.4f} секунд")
        return result

    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()

```
### Результат.
![ex1](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Practic/101.png)

## Выводы
timing_decorator(func) - функция-декоратор, принимающая функцию func. Внутри определена функция wrapper, которая измеряет время выполнения функции, вызывает её и выводит информацию о времени выполнения.
wrapper(*args, **kwargs) - функция-обертка, принимающая переменное количество аргументов и ключевых аргументов. Замеряет время до и после выполнения функции func, выводит информацию о времени выполнения и возвращает результат выполнения функции.
@timing_decorator - декоратор, примененный к функции fibonacci.
fibonacci() - функция, вычисляющая числа Фибоначчи до 200-го элемента и выводящая их. Замеряется время её выполнения с использованием декоратора.
В блоке __main__ вызывается функция fibonacci(). В результате выполнения выводится информация о времени выполнения функции.


### 2) Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла

```python
def read_file(file_name):
    try:
        with open(file_name, 'r') as file:
            content = file.read()
            if not content:
                raise Exception("файл пустой")
            else:
                print("Содержимое файла:")
                print(content)
    except FileNotFoundError:
        print(f"Файл '{file_name}' не найден")
    except Exception as e:
        print(e)

# Проверяем пустой файл
read_file('empty_file.txt')
print('-------------------')
# Проверяем файл с информацией
read_file('data_file.txt')
```
### Результат.
![ex2](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Practic/102.png)

## Выводы
read_file(file_name) - функция, которая принимает имя файла в качестве аргумента. Внутри функции используется блок try-except для обработки исключений.


### 3) Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
def add_two_and_number():
    try:
        user_input = input("Введите число: ")
        number = float(user_input)
        result = 2 + number
        print(f"Результат сложения 2 и {number} равен {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")

# Тесты
add_two_and_number()  # Ввод корректного числа
add_two_and_number()  # Ввод строки
add_two_and_number()  # Ввод некорректного числа

```
### Результат.
![ex3](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Practic/103.png)

## Выводы
add_two_and_number() - функция, которая запрашивает у пользователя ввод числа, пытается преобразовать введенное значение в число и затем складывает его с числом 2. В блоке try-except обрабатывается исключение ValueError, которое может возникнуть при некорректном вводе (например, ввод строки вместо числа).


### 4) Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций. Декораторы, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс декоратора, две как-то связанными с ним функциями, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода

```python
def simple_decorator(func):
    # Объявляем внутреннюю функцию-обертку (wrapper), которая будет выполняться вместо оригинальной функции
    def wrapper(*args, **kwargs):
        # Выводим название вызванной функции перед её выполнением
        print(f"Вызвана функция {func.__name__}")
        
        # Вызываем оригинальную функцию с переданными аргументами и ключевыми словами
        result = func(*args, **kwargs)
        
        # Возвращаем результат выполнения функции
        return result
    
    # Возвращаем функцию-обертку в качестве результата работы декоратора
    return wrapper

# Используем декоратор для двух функций

@simple_decorator
def greet(name):
    # Выводим приветствие с переданным именем
    print(f"Привет, {name}!")

@simple_decorator
def square(x):
    # Возвращаем квадрат переданного числа
    return x ** 2

# Тестируем функции

greet("Анна")  # Декоратор выведет: Вызвана функция greet
result = square(5)  # Декоратор выведет: Вызвана функция square

```
### Результат.
![ex4](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Practic/104.png)

## Выводы
В блоке __main__ используются две функции, greet и square, к которым применен декоратор @simple_decorator. При вызове этих функций выводится сообщение о вызове функции, и в случае square результат возвращается и сохраняется в переменной result.


### 5) Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода. Исключения, которые использовались ранее в работе нельзя воссоздавать. Результатом выполнения задачи будет: класс исключения, код к котором в двух местах используется это исключение, скриншот консоли с выполненной программой и подробные комментарии, которые будут описывать работу вашего кода.

```python
try:
    # Запрашиваем у пользователя ввод числа
    user_input_1 = input("Введите число: ")

    # Пытаемся преобразовать введенное значение в число
    number_1 = float(user_input_1)

except ValueError:
    # Если введенное значение не является числом, вызываем собственное исключение
    raise InvalidInputError("Некорректный ввод. Ожидалось число.")

# Пример использования исключения во втором фрагменте кода

try:
    # Запрашиваем у пользователя ввод числа
    user_input_2 = input("Введите число: ")

    # Пытаемся преобразовать введенное значение в число
    number_2 = float(user_input_2)

except ValueError:
    # Если введенное значение не является числом, вызываем собственное исключение
    raise InvalidInputError("Некорректный ввод. Ожидалось число.")
```
### Результат.
![ex5](https://github.com/kokac16/OZIVT_OKHLUPIN/blob/theme_10/pic/Practic/105.png)

## Выводы
Код содержит два блока try-except, каждый из которых запрашивает у пользователя ввод числа, пытается преобразовать введенное значение в число и обрабатывает исключение ValueError, если ввод не является числом. В случае ошибки вызывается собственное исключение InvalidInputError с сообщением "Некорректный ввод. Ожидалось число."

## Общий вывод по теме
Тема "Декораторы и исключения" включает в себя изучение декораторов, которые являются функциями высшего порядка, способных изменять поведение других функций. Синтаксис использования декораторов включает определение и применение декоратора к функции или классу. Декораторы могут быть предопределены в сторонних библиотеках или созданы самостоятельно как для функций, так и для классов.
Тема также охватывает работу с исключениями, их иерархию и метод "бросания исключениями". Исключения предоставляют механизм обработки ошибок, а пользователь может создавать свои собственные исключения для более гибкого управления ошибками в программе.